*MAT_ENHANCED_COMPOSITE_DAMAGE_TITLE
$HMNAME MATERIAL$ID$S$TITLE$
$ID$$DENSITY$$E1$$E2$$E1$$MU$$MU$$MU$
$GAB$$GBC$$GAB$       0.0$DEFINE$       0.0
       0.0       0.0       0.0       0.0       0.0       0.0       0.0
       0.0       0.0       0.0       0.0       0.0       0.0       0.0       0.0
1.00000E-9       0.0       1.0$FBRT$$YCFAC$       0.0       0.0       0.0
$XC$$XT$$YC$$YT$       0.0      55.0       0.0
